<<<<<<< HEAD
theme: jekyll-theme-slate
title: [Personal Page]
description: [A short description of your site's purpose]
=======
theme: jekyll-theme-tactile
>>>>>>> 1c1ac0a7110d6a41d13ff919433013982b3ac253
